### PR TITLE
Fix broken st2-self-check script

### PR DESCRIPTION
**Pull request by Kami**
This pull request fixes an issue introduced in #150 which I described here - https://github.com/StackStorm/st2tests/pull/150#issuecomment-480762617.

``tests`` pack is only used for end to end and st2-self-check script tests. As such, all the actions inside that pack should follow that action format.

To fix the issue, I made the following changes:

1. Moved new action inside ``fixtures`` pack - that's where "fixture" actions should live
2. Added new ``tests.test_render_config_context`` action which uses the fixture action and tests render config context functionality

This will also require changed in StackStorm/st2 repo. We can likely get rid of all the "clone st2tests" pack change from this PR - https://github.com/StackStorm/st2/issues/4567.

### CODE REVIEW

**Comment by Kami** [comment]
Confirmed it's working:

```bash
Deleting 'st2tests' directory from /home/ubuntu.
~
Attempting Test tests.test_inquiry_chain...OK! (47s)
Attempting Test tests.test_inquiry_mistral...OK! (49s)
Attempting Test tests.test_key_triggers...OK! (33s)
Attempting Test tests.test_pack_install_tool...OK! (10s)
Attempting Test tests.test_packs_pack...OK! (76s)
Attempting Test tests.test_quickstart...OK! (21s)
Attempting Test tests.test_quickstart_key...OK! (6s)
Attempting Test tests.test_quickstart_local_script_actions...OK! (13s)
Attempting Test tests.test_quickstart_passive_sensor...OK! (7s)
Attempting Test tests.test_quickstart_polling_sensor...OK! (4s)
Attempting Test tests.test_quickstart_python_actions...OK! (11s)
Attempting Test tests.test_quickstart_remote_script_actions...OK! (14s)
Attempting Test tests.test_quickstart_rules...OK! (62s)
Attempting Test tests.test_quickstart_trace...OK! (16s)
Attempting Test tests.test_render_config_context...OK! (5s)
```

**Comment by jinpingh** [comment]
@Kami  Not sure how it is working for moving `packs/tests/actions/render_config_context.py → packs/fixtures/render_config_context.py`
Should it be moved under `packs/fixtures/actions` directory?

If action is moved to `fixtures` pack, it will break https://github.com/StackStorm/st2/blob/master/st2tests/integration/orquesta/test_wiring.py integration test case `test_config_context_renders`.  https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/workflows/render_config_context.yaml and   https://github.com/StackStorm/st2/blob/master/tools/launchdev.sh need to be changed.

**Comment by Kami** [comment]
> @Kami Not sure how it is working for moving packs/tests/actions/render_config_context.py → packs/fixtures/render_config_context.py
Should it be moved under packs/fixtures/actions directory?

Yeah, I've fixed that locally already, but haven't pushed the changes yet - I've pushed them now.

I will look into the StackStorm/st2 change - one option would be to simply move that action to the examples pack (IIRC, we already have a similar action there).

**Comment by Kami** [comment]
I've pushed latest changes.

Per our discussion on Slack, I moved action to fixtures pack https://github.com/StackStorm/st2/pull/4625.

**Pull request merged**
